--CREATING TABLE--

CREATE TABLE USER_TB(
	USERID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(100) NOT NULL,
	REGISTRATIONDATE DATETIME NOT NULL,
	PRIMARY KEY(USERID))
GO

CREATE TABLE TASK_TB(
	TASKID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	DATE DATE NOT NULL,
	HOUR TIME(7) NOT NULL,
	DESCRIPTION NVARCHAR(100) NOT NULL,
	PRIORITY NVARCHAR(15) NOT NULL,
	USERID UNIQUEIDENTIFIER NOT NULL,
	PRIMARY KEY(TASKID),
	FOREIGN KEY(USERID)
		REFERENCES USER_TB(USERID))
GO

	--CONSULTING TABLES--

	SELECT * FROM USER_TB
	GO

	SELECT * FROM TASK_TB
	GO