CREATE TABLE USER_TB(
	USERID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(100) NOT NULL,
	REGISTRATIONDATE NVARCHAR(100) NOT NULL,
	PRIMARY KEY(USERID))
	GO

	SELECT * FROM USER_TB
	GO