CREATE TABLE USER_TB(
	USERID UNIQUEIDENTIFIER NOT NULL,
	NAME NVARCHAR(150) NOT NULL,
	EMAIL NVARCHAR(150) NOT NULL UNIQUE,
	PASSWORD NVARCHAR(150) NOT NULL,
	REGISTRATIONDATE DATETIME NOT NULL,
	PRIMARY KEY(USERID))

GO

SELECT * FROM USER_TB
GO